name: CI

on:
    pull_request:
        branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path:
            ~/.gradle/caches
            ~/.gradle/wrapper
          key:
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Gradle Build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-gradle-build-${{ github.sha }}
          restore-keys: |
              ${{ runner.os }}-gradle-build-

      - name: Grant execute permission for gradlew
        working-directory: ./noonsub-backend
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./noonsub-backend
        run: ./gradlew clean build --build-cache